name: ASCII Workflow

on:
  - push

jobs: 
    first_job: 
        name: ascii script
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: print current directory
              run: pwd

            - name: Execute Shell Script
              run: ./ascii-script.sh
