name: Deploy to Environments

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: dev
      username: ${{ vars.DOCKER_USERNAME }}
    secrets:
      password: ${{ secrets.DOCKER_PASSWORD }}

  deploy_staging:
    needs: deploy_dev
    uses: ./.github/workflows/reusable.yml
    with:
      environment: staging
      username: ${{ vars.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  deploy_prod:
    needs: deploy_staging
    uses: ./.github/workflows/reusable.yml
    with:
      environment: production
      username: ${{ vars.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
