name: Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      username:
        required: true
        type: string
    secrets:
      password:
        required: true

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: resume

jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ inputs.username }}/${{ env.IMAGE_NAME }}:latest .

      -  name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ inputs.username  }}
          password: ${{ secrets.password }}
      

      - name: Docker Publish 
        run: docker push ${{ env.CONTAINER_REGISTRY }}/${{ inputs.username }}/${{ env.IMAGE_NAME }}:latest

  docker_deploy:
    needs: docker_build
    runs-on: ubuntu-latest 
    steps:
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
          username: ${{ inputs.username  }}
          password: ${{ secrets.password }}
     - name: Docker Deploy
       run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ inputs.username }}/${{ env.IMAGE_NAME }}:latest
